#!/usr/bin/env bash
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
HELP="Run an interactive pod in the cluster for debugging purposes. Pod is removed when shell exists.\n\
Default image is 'centos:latest' and the first argument will change this. Image must have bash installed.\n\
Example:\n
  kubectl debug\n
  kubectl debug google/cloud-sdk:alpine"
if [[ "$1" == "help" || "$1" == "-h" ]]
then
  echo -e $HELP
  exit 0
fi
IMAGE=${1:-centos:latest}
kubectl run -n ${KUBECTL_PLUGINS_CURRENT_NAMESPACE} -it --rm --restart=Never kube-shell --image ${IMAGE} -- bash