#!/usr/bin/env bash
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

HELP="Get logs for a pod from list\n\
Display list of all pods to select from.\n\
If pod has multiple containers, another list is shown to choose from.\n\n
Example:\n\
  kubectl podlogs\n
  kubectl podlogs -f\n
"
if [[ "$1" == "help" || "$1" == "-h" ]]
then
  echo -e $HELP
  exit 0
fi

function _kube_list_pods() {
  NS_ARG="--all-namespaces"
  [[ -n "$1" ]] && NS_ARG="-n ${1}"

  IFS=';' read -ra pods <<< "$(kubectl get pods $NS_ARG -o go-template='{{range .items}}{{.metadata.name}}:{{.metadata.namespace}}:{{.status.phase}}{{"\n"}}{{end}}' | sort -k 2 -k 1 -t: | tr '\n' ';')"
  local count=1
  lines=$(for i in ${pods[@]}; do
    IFS=":" read -ra TOKS <<< "${i}"
    printf "  $count) ${TOKS[0]}\t${TOKS[1]}\t${TOKS[2]}\n"
    ((count=count+1))
  done | column -t)
  count=$(echo "$lines" | wc -l)
  echo "$lines" >&2
  local sel=0
  while [[ $sel -lt 1 || $sel -gt $count ]]; do
    read -p "Select a Pod: " sel >&2
  done
  echo "${pods[(sel-1)]}"
}

function _kube_list_pod_containers() {
  POD=$1
  NAMESPACE=$2
  IFS=';' read -ra items <<< "$(kubectl get pod ${POD} -n ${NAMESPACE} -o go-template='{{range .spec.containers}}{{.name}}{{"\n"}}{{end}}' | tr '\n' ';')"
  local count=1
  lines=$(for i in ${items[@]}; do
    printf "  $count) ${i}\n"
    ((count=count+1))
  done | column -t)
  count=$(echo "$lines" | wc -l)
  if [[ $count -gt 1 ]]; then
    printf "\nPod has multiple containers:\n" >&2
    echo "$lines" >&2
    local sel=0
    while [[ $sel -lt 1 || $sel -gt $count ]]; do
      read -p "Select a Container: " sel >&2
    done
  fi
  echo "${items[(sel-1)]}"
}

SEL=$(_kube_list_pods)
IFS=":" read -ra POD <<< "${SEL}"

if [[ "${POD[2],,}" != "running" ]]; then
  echo "ERROR: Pod ${POD[0]} is not running" >&2
  exit 1
fi

SEL=$(_kube_list_pod_containers ${POD[0]} ${POD[1]})

kubectl -n ${POD[1]} logs "${POD[0]}" -c ${SEL} $@